[package]
name = "proof_of_proximity"
version = "0.1.0"
authors = ["JaniAnttonen <jani.anttonen@protonmail.ch>"]
edition = "2018"

[dependencies]
ramp = "0.5.6"
sha3 = "0.8.2"
rand = "0.7.2"
rand_core = "0.5.1"
