[package]
name = "proof_of_latency"
version = "0.2.0"
authors = ["Jani Anttonen <jani.anttonen@protonmail.ch>"]
edition = "2018"

[dependencies]
ramp = "0.5.6"
sha3 = "0.8.2"
rand = "0.7.2"
rand_core = "0.5.1"
libp2p = "0.18.1" 
async-std = "1.5.0"
env_logger = "0.7.1" 
primal = "0.2"

[dev-dependencies.cargo-husky]
version = "1"
features = ["precommit-hook", "run-cargo-fmt", "run-cargo-test", "run-cargo-clippy"]
