name = "proof_of_latency"

[defaults]
builder = "docker:rust"
runner = "local:docker"

[builders."docker:rust"]
enabled = true

[runners."local:docker"]
enabled = true

[[testcases]]
name = "peering"
instances = { min = 2, max = 20, default = 2 }

